### ISSUE TITLE
delayed display in PTB 

### ISSUE THREAD

**Issue by giamac** [OpenNFT/OpenNFT#59] opened 2019-12-11 19:41 UTC
The presentation of the instructions and feedback in PTB are delayed (Yury had the same issue on an older setup). It only recovers after more or less 40 images. 
We also started the PTB Matlab helper engine in -desktop mode to debug, but encountered the same problem. PTB seems to get stuck in the displayFeedback script.

**Comment by tiborauer** [comment] 2019-12-12 11:40
We may need to consider using PsychoPy rather than PTB.

**Comment by ykoush** [comment] 2019-12-13 21:38
@tiborauer true, but still have to fix

**Comment by da0c** [comment] 2019-12-15 19:02
@giamac - let me know your PTB version, from Psychtoolbox\Contents.m.
Probably, the problem is caused by the new PTB version.

**Comment by giamac** [comment] 2019-12-16 08:06
@da0c 
Version 3.0.15      8 November 2018

**Comment by ykoush** [comment] 2019-12-18 00:08
We couldn't reproduce this error on 2 desktop PCs and will be testing it on my laptop.

**Comment by da0c** [comment] 2019-12-18 09:15
We couldn't reproduce the bug on one of our PCs with the same PTB Version (3.0.15 8 November 2018).
So, PTB's version is not a reason.

**Comment by ykoush** [comment] 2020-03-06 23:28
We tested this issue on my laptop and found that this delay disappears if just Screen('DrawText') PTB-3  function is commented out. This concerns all the feedback types where it was used. Other Screen functions don't delay anything, e.g when drawing images as textures or drwaing fixation dots, arrow, etc. TBC, but may be @giamac could try to comment out Screen('DrawText') on your PC and let us know.

**Comment by ykoush** [comment] 2020-03-06 23:30
One possible solution is to replace Screen('DrawText') with a prepared texture of the required Text.

**Comment by da0c** [comment] 2020-03-07 07:26
The problem with PTB DrawText is known. See - https://stackoverflow.com/questions/50450921/psychtoolbox-drawtext-causes-so-many-missed-flips-matlab

So, I think we can close this issue.

**Comment by da0c** [comment] 2020-03-07 07:29
Or, better we will wait for feedback from @giamac

**Comment by giamac** [comment] 2020-03-11 10:50
Sorry for my late response: I just tried your fix and the delay disappeared after commenting "DrawText" out. I guess you found the issue

**Comment by ykoush** [comment] 2020-03-11 16:12
This is great to know what needs to be fixed. But commenting out doesn't fix, I'll be working on a few options to fix this problem for OpenNFT. In the mean time, the users know where it comes from.

**Comment by da0c** [comment] 2020-03-12 05:49
Actually, in our experiments in Yury's environment, DrawText leads to a large delay of about 30 seconds only for the first call. So, a possible workaround is to place the first call of DrawText in the setup stage, just show smth. like "HELLO" for "warming-up". @giamac you may test this workaround in your case.

**Comment by ykoush** [comment] 2020-06-25 01:58
I was able to resolve this issue on my PC, Matlab 2018a, by updating PTB-3 to 3.0.16 using UpdatePsychtoolbox and by updating GStreamer-1.16.0 MSVC runtime. For more info you can see their webpage.
It would be helpful if @giamac could double check if it works for his PC and we could close this issue.

**Comment by giamac** [comment] 2020-06-25 13:28
I upgraded Psychtoolbox and GStreamer-1.16.2 MSVC runtime. The update solved the issue for the newest version, thank you. I think you can close the issue.
However another issue, the setup with the currently provided *.ini and *.json example files in the configs folder only work with the /matlab/utils/loadProtocolData.m version from march 1st, but not with the most recent loadProtocalData.m (commits today).  OpenNFT now demands a BaselineName, which is not present in the currently available configs.

**Comment by ykoush** [comment] 2020-06-25 16:06
Great! Wrt 2nd issue, thank you for noticing, I just worked with another version of configs and updated the code for them, this should be working as it was now.

**Closed by ykoush** 2020-06-25 16:06 UTC
Labels: question
